/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'case-studies': CaseStudy;
    posts: Post;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use full route paths such as / or /services/maintenance-support
   */
  pathname: string;
  status: 'draft' | 'published';
  metaTitle?: string | null;
  metaDescription: string;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    primaryActionLabel?: string | null;
    primaryActionHref?: string | null;
    secondaryActionLabel?: string | null;
    secondaryActionHref?: string | null;
    workPreviewStrip?: (number | null) | Media;
    websitePreviewLabel?: string | null;
    media?: (number | null) | Media;
  };
  summary?: string | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading?: string | null;
            tone?: ('default' | 'muted' | 'accent') | null;
            content: string;
            /**
             * Optional image displayed on the left side. Will be automatically desaturated for use as a background graphic.
             */
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdownSection';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            items: {
              badge?: string | null;
              title: string;
              description: string;
              href?: string | null;
              linkLabel?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            items: {
              title?: string | null;
              description: string;
              /**
               * Enter a valid Phosphor icon name (e.g., Gear, ArrowRight, CheckCircle, ShieldCheck). Leave blank to use the default gradient bullet.
               */
              icon?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletList';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            steps: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            selectedCaseStudies: (number | CaseStudy)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyHighlights';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            tiers: {
              name: string;
              priceLabel: string;
              tagline: string;
              responseWindow?: string | null;
              highlighted?: boolean | null;
              note?: string | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              features: {
                feature: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTiers';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body: string;
            tone?: ('plum' | 'green' | 'neutral') | null;
            primaryActionLabel?: string | null;
            primaryActionHref?: string | null;
            secondaryActionLabel?: string | null;
            secondaryActionHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            emailLabel?: string | null;
            email?: string | null;
            phoneLabel?: string | null;
            phone?: string | null;
            calendlyLabel?: string | null;
            calendlyUrl?: string | null;
            embedUrl?: string | null;
            note?: string | null;
            responseWindows?:
              | {
                  label: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMethods';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            populateBy?: ('collection' | 'selection') | null;
            relationTo?: 'posts' | null;
            categories?: (number | Category)[] | null;
            limit?: number | null;
            selectedDocs?:
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archive';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  summary: string;
  sector?: string | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Use this for seed/demo case studies until real anonymized stories replace them.
   */
  isRepresentative?: boolean | null;
  publishedAt: string;
  challenge: string;
  approach: string;
  outcome: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  excerpt: string;
  authorName?: string | null;
  publishedAt: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pathname?: T;
  status?: T;
  metaTitle?: T;
  metaDescription?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        primaryActionLabel?: T;
        primaryActionHref?: T;
        secondaryActionLabel?: T;
        secondaryActionHref?: T;
        workPreviewStrip?: T;
        websitePreviewLabel?: T;
        media?: T;
      };
  summary?: T;
  layout?:
    | T
    | {
        markdownSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              tone?: T;
              content?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    linkLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bulletList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseStudyHighlights?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              selectedCaseStudies?: T;
              id?: T;
              blockName?: T;
            };
        pricingTiers?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    priceLabel?: T;
                    tagline?: T;
                    responseWindow?: T;
                    highlighted?: T;
                    note?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              tone?: T;
              primaryActionLabel?: T;
              primaryActionHref?: T;
              secondaryActionLabel?: T;
              secondaryActionHref?: T;
              id?: T;
              blockName?: T;
            };
        contactMethods?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              emailLabel?: T;
              email?: T;
              phoneLabel?: T;
              phone?: T;
              calendlyLabel?: T;
              calendlyUrl?: T;
              embedUrl?: T;
              note?: T;
              responseWindows?:
                | T
                | {
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        archive?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              populateBy?: T;
              relationTo?: T;
              categories?: T;
              limit?: T;
              selectedDocs?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  summary?: T;
  sector?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featured?: T;
  isRepresentative?: T;
  publishedAt?: T;
  challenge?: T;
  approach?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  authorName?: T;
  publishedAt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  tagline: string;
  siteUrl: string;
  contactEmail: string;
  phone?: string | null;
  calendlyUrl?: string | null;
  linkedinUrl?: string | null;
  ownerLine: string;
  footerNote?: string | null;
  defaultMetaTitle: string;
  defaultMetaDescription: string;
  trustPills?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload the logo image to appear in the site header.
   */
  logo?: (number | null) | Media;
  /**
   * Upload the logo image to appear in the site footer. Display will be constrained to max 2rem.
   */
  footerLogo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  siteUrl?: T;
  contactEmail?: T;
  phone?: T;
  calendlyUrl?: T;
  linkedinUrl?: T;
  ownerLine?: T;
  footerNote?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  trustPills?:
    | T
    | {
        label?: T;
        id?: T;
      };
  logo?: T;
  footerLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}